package com.xg.admin.pojo.server;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 *
 * Generated by the rapid-generator.  DO NOT EDIT!!!
 * 
 * @author zhangyaping email:yapingzhang_beta@163.com
 * @version 1.0, 2014年11月08日
 *
 */
public class ServerData implements Serializable {
	private static final long serialVersionUID = 5454155825314635342L;

	private java.lang.Integer serverId;
	private java.lang.String serverIp;
	private java.lang.Integer serverPort;

	public java.lang.Integer getServerId() {
		return serverId;
	}

	public void setServerId(java.lang.Integer serverId) {
		this.serverId = serverId;
	}

	public java.lang.String getServerIp() {
		return serverIp;
	}

	public void setServerIp(java.lang.String serverIp) {
		this.serverIp = serverIp;
	}

	public java.lang.Integer getServerPort() {
		return serverPort;
	}

	public void setServerPort(java.lang.Integer serverPort) {
		this.serverPort = serverPort;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(getServerId()).toHashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof ServerData == false) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		ServerData other = (ServerData) obj;
		return new EqualsBuilder().append(getServerId(), other.getServerId()).isEquals();
	}
}
