package com.xg.admin.pojo.task;

import java.io.Serializable;
import java.util.List;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 *
 * Generated by the rapid-generator.  DO NOT EDIT!!!
 * 
 * @author zhangyaping email:yapingzhang_beta@163.com
 * @version 1.0, 2014年12月04日
 *
 */
public class TaskRewardData implements Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//columns START
    /**
     * 序号       db_column: F_id 第1个
     */
	private java.lang.Integer  id;
    /**
     * 任务id       db_column: F_task_id 第2个
     */
	private java.lang.Integer  taskId;
    /**
     * 奖励丰厚级别       db_column: F_reward_grade 第3个
     */
	private java.lang.Integer  rewardGrade;
    /**
     * 奖励物品，格式： {道具ID*道具数量*包裹类型*过期时间}*，多个以分号分隔       db_column: F_reward_goods 第4个
     */
	private java.lang.String  rewardGoods;
    /**
     * 金币奖励       db_column: F_gold 第5个
     */
	private java.lang.Integer  gold;
    /**
     * 奖励元宝数量（钻石）       db_column: F_yuanbao 第6个
     */
	private java.lang.Integer  yuanbao;
    /**
     * 奖励公会贡献度       db_column: F_contribution 第7个
     */
	private java.lang.Integer  contribution;
    /**
     * 奖励称号id       db_column: F_title 第8个
     */
	private java.lang.Integer  title;
    /**
     * 经验奖励       db_column: F_exp 第9个
     */
	private java.lang.Integer  exp;
    /**
     * 全服公告       db_column: F_notice 第10个
     */
	private java.lang.String  notice;
	/**
     * 战队经验奖励       db_column: F_team_exp 第11个
     */
	private java.lang.Integer  teamExp;
	//columns END

	public TaskRewardData(){
	}
	
	private List<String> goodsTexts;
	private List<String> goodsValues;

	public TaskRewardData(
		java.lang.Integer id
	){
		this.id = id;
	}

	/**
	 * 序号 db_column: t_task_reward.F_id
	 */	
	public void setId(java.lang.Integer value) {
		this.id = value;
	}
	
	/**
     * 序号 db_column: t_task_reward.F_id
     */
	public java.lang.Integer getId() {
		return this.id;
	}
	/**
	 * 任务id db_column: t_task_reward.F_task_id
	 */	
	public void setTaskId(java.lang.Integer value) {
		this.taskId = value;
	}
	
	/**
     * 任务id db_column: t_task_reward.F_task_id
     */
	public java.lang.Integer getTaskId() {
		return this.taskId;
	}
	/**
	 * 奖励丰厚级别 db_column: t_task_reward.F_reward_grade
	 */	
	public void setRewardGrade(java.lang.Integer value) {
		this.rewardGrade = value;
	}
	
	/**
     * 奖励丰厚级别 db_column: t_task_reward.F_reward_grade
     */
	public java.lang.Integer getRewardGrade() {
		return this.rewardGrade;
	}
	/**
	 * 奖励物品，格式： {道具ID*道具数量*包裹类型*过期时间}*，多个以分号分隔 db_column: t_task_reward.F_reward_goods
	 */	
	public void setRewardGoods(java.lang.String value) {
		this.rewardGoods = value;
	}
	
	/**
     * 奖励物品，格式： {道具ID*道具数量*包裹类型*过期时间}*，多个以分号分隔 db_column: t_task_reward.F_reward_goods
     */
	public java.lang.String getRewardGoods() {
		return this.rewardGoods;
	}
	/**
	 * 金币奖励 db_column: t_task_reward.F_gold
	 */	
	public void setGold(java.lang.Integer value) {
		this.gold = value;
	}
	
	/**
     * 金币奖励 db_column: t_task_reward.F_gold
     */
	public java.lang.Integer getGold() {
		return this.gold;
	}
	/**
	 * 奖励元宝数量（钻石） db_column: t_task_reward.F_yuanbao
	 */	
	public void setYuanbao(java.lang.Integer value) {
		this.yuanbao = value;
	}
	
	/**
     * 奖励元宝数量（钻石） db_column: t_task_reward.F_yuanbao
     */
	public java.lang.Integer getYuanbao() {
		return this.yuanbao;
	}
	/**
	 * 奖励公会贡献度 db_column: t_task_reward.F_contribution
	 */	
	public void setContribution(java.lang.Integer value) {
		this.contribution = value;
	}
	
	/**
     * 奖励公会贡献度 db_column: t_task_reward.F_contribution
     */
	public java.lang.Integer getContribution() {
		return this.contribution;
	}
	/**
	 * 奖励称号id db_column: t_task_reward.F_title
	 */	
	public void setTitle(java.lang.Integer value) {
		this.title = value;
	}
	
	/**
     * 奖励称号id db_column: t_task_reward.F_title
     */
	public java.lang.Integer getTitle() {
		return this.title;
	}
	/**
	 * 经验奖励 db_column: t_task_reward.F_exp
	 */	
	public void setExp(java.lang.Integer value) {
		this.exp = value;
	}
	
	/**
     * 经验奖励 db_column: t_task_reward.F_exp
     */
	public java.lang.Integer getExp() {
		return this.exp;
	}
	/**
	 * 全服公告 db_column: t_task_reward.F_notice
	 */	
	public void setNotice(java.lang.String value) {
		this.notice = value;
	}
	
	/**
     * 全服公告 db_column: t_task_reward.F_notice
     */
	public java.lang.String getNotice() {
		return this.notice;
	}
	
	/**
	 * 战队经验奖励 db_column: t_task_reward.F_team_exp
	 */	
	public void setTeamExp(java.lang.Integer value) {
		this.teamExp = value;
	}
	
	/**
     * 战队经验奖励 db_column: t_task_reward.F_team_exp
     */
	public java.lang.Integer getTeamExp() {
		return this.teamExp;
	}
	
	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
	
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(getId()).toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof TaskRewardData == false){ return false;}
		if(this == obj) {return true;}
		TaskRewardData other = (TaskRewardData)obj;
		return new EqualsBuilder().append(getId(),other.getId()).isEquals();
	}

	public List<String> getGoodsTexts() {
		return goodsTexts;
	}

	public void setGoodsTexts(List<String> goodsTexts) {
		this.goodsTexts = goodsTexts;
	}

	public List<String> getGoodsValues() {
		return goodsValues;
	}

	public void setGoodsValues(List<String> goodsValues) {
		this.goodsValues = goodsValues;
	}
}

